name: Python Package using Conda and Rust

on: [push]

jobs:
  build-linux:
    name: Build and Test Linux
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: strainr
          environment-file: environment.yml

      - name: Install Python dependencies (conda)
        shell: bash -l {0}
        run: |
          echo "Attempting to install dependencies from environment.yml"
          # Should already be done by setup-miniconda, but here for debug.
          conda list

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install Maturin
        shell: bash -l {0}
        run: pip install maturin

      - name: Compile and install Rust extension (kmer_counter_rs)
        shell: bash -l {0}
        run: |
          echo "Building and installing Rust extension..."
          cd kmer_counter_rs
          maturin build --release -o ../target/wheels 
          cd ..
          pip install target/wheels/*.whl
          python -c "import kmer_counter_rs; print('kmer_counter_rs imported successfully')"

      - name: Lint and Format Check with Ruff
        shell: bash -l {0}
        run: |
          echo "Running ruff check (linting)..."
          ruff check .
          echo "Running ruff format --check (format check)..."
          ruff format --check .

      - name: Test with pytest and Coverage
        shell: bash -l {0}
        run: |
          echo "Running pytest with coverage..."
          pytest tests/ --cov=strainr --cov-report=xml --cov-report=term

      - name: Upload Coverage Report (Optional)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: coverage-report
          path: coverage.xml
          retention-days: 7